### ISSUE TITLE
Some questions about datasets

### ISSUE THREAD

**Issue by DreamMaker777** [araujoalexandre/FocusStackingDataset#1]
Thanks for your work! I meet some problem when I try to run your code:
In Class FocusDataset, something went wrong with "crop_path = f'{burst_path}/crops{self.dataset_id}/crop{i}.pkl'". I searched the dataset folder but did not find such files named "*.pkl", and I did not find the code to generate these "*.pkl" files. Could you tell me how to generate these files? Thank you!

**Comment by araujoalexandre** [comment]
Thank you for reaching out! Indeed I forgot to add the scripts for generating the pkl files in the repo, I just added these files in the scripts folder. 
Best,

**Comment by DreamMaker777** [comment]
Thanks a lot! This work provides a new method for multi-focus image fusion, and I'm looking forward to your new work!

**Comment by araujoalexandre** [comment]
Thank you for your interest! I am going to close this issue, don't hesitate to open a new one if you have another problem. 
Best
